/* eslint-disable */

export const AllTypesProps: Record<string,any> = {
	boolean_filter_operators:{

	},
	certificates_filter:{
		id:"string_filter_operators",
		user_created:"string_filter_operators",
		date_created:"date_filter_operators",
		date_created_func:"datetime_function_filter_operators",
		date_updated:"date_filter_operators",
		date_updated_func:"datetime_function_filter_operators",
		full_name:"string_filter_operators",
		ic:"string_filter_operators",
		phone:"string_filter_operators",
		cda_number:"string_filter_operators",
		total_days:"number_filter_operators",
		test_score:"string_filter_operators",
		marks:"string_filter_operators",
		location:"string_filter_operators",
		course:"string_filter_operators",
		course_start_date:"string_filter_operators",
		course_end_date:"string_filter_operators",
		email:"string_filter_operators",
		certificate:"string_filter_operators",
		number_title:"string_filter_operators",
		position:"string_filter_operators",
		_and:"certificates_filter",
		_or:"certificates_filter"
	},
	create_student_login_input:{
		date_created:"Date"
	},
	create_verified_details_input:{
		date_created:"Date",
		date_updated:"Date"
	},
	Date: `scalar.Date` as const,
	date_filter_operators:{
		_between:"GraphQLStringOrFloat",
		_nbetween:"GraphQLStringOrFloat"
	},
	datetime_function_filter_operators:{
		year:"number_filter_operators",
		month:"number_filter_operators",
		week:"number_filter_operators",
		day:"number_filter_operators",
		weekday:"number_filter_operators",
		hour:"number_filter_operators",
		minute:"number_filter_operators",
		second:"number_filter_operators"
	},
	GraphQLStringOrFloat: `scalar.GraphQLStringOrFloat` as const,
	JSON: `scalar.JSON` as const,
	Mutation:{
		create_verified_details_items:{
			filter:"verified_details_filter",
			data:"create_verified_details_input"
		},
		create_verified_details_item:{
			data:"create_verified_details_input"
		},
		create_student_login_items:{
			filter:"student_login_filter",
			data:"create_student_login_input"
		},
		create_student_login_item:{
			data:"create_student_login_input"
		},
		update_verified_details_items:{
			filter:"verified_details_filter",
			data:"update_verified_details_input"
		},
		update_verified_details_batch:{
			filter:"verified_details_filter",
			data:"update_verified_details_input"
		},
		update_verified_details_item:{
			data:"update_verified_details_input"
		},
		update_certificates_items:{
			filter:"certificates_filter",
			data:"update_certificates_input"
		},
		update_certificates_batch:{
			filter:"certificates_filter",
			data:"update_certificates_input"
		},
		update_certificates_item:{
			data:"update_certificates_input"
		},
		update_student_login_items:{
			filter:"student_login_filter",
			data:"update_student_login_input"
		},
		update_student_login_batch:{
			filter:"student_login_filter",
			data:"update_student_login_input"
		},
		update_student_login_item:{
			data:"update_student_login_input"
		}
	},
	number_filter_operators:{
		_eq:"GraphQLStringOrFloat",
		_neq:"GraphQLStringOrFloat",
		_in:"GraphQLStringOrFloat",
		_nin:"GraphQLStringOrFloat",
		_gt:"GraphQLStringOrFloat",
		_gte:"GraphQLStringOrFloat",
		_lt:"GraphQLStringOrFloat",
		_lte:"GraphQLStringOrFloat",
		_between:"GraphQLStringOrFloat",
		_nbetween:"GraphQLStringOrFloat"
	},
	Query:{
		verified_details:{
			filter:"verified_details_filter"
		},
		verified_details_by_id:{

		},
		verified_details_aggregated:{
			filter:"verified_details_filter"
		},
		certificates:{
			filter:"certificates_filter"
		},
		certificates_by_id:{

		},
		certificates_aggregated:{
			filter:"certificates_filter"
		},
		student_login:{
			filter:"student_login_filter"
		},
		student_login_by_id:{

		},
		student_login_aggregated:{
			filter:"student_login_filter"
		}
	},
	string_filter_operators:{

	},
	student_login_filter:{
		id:"string_filter_operators",
		date_created:"date_filter_operators",
		date_created_func:"datetime_function_filter_operators",
		email:"string_filter_operators",
		phone:"string_filter_operators",
		ic:"string_filter_operators",
		_and:"student_login_filter",
		_or:"student_login_filter"
	},
	update_certificates_input:{
		date_created:"Date",
		date_updated:"Date"
	},
	update_student_login_input:{
		date_created:"Date"
	},
	update_verified_details_input:{
		date_created:"Date",
		date_updated:"Date"
	},
	verified_details_filter:{
		id:"string_filter_operators",
		user_created:"string_filter_operators",
		date_created:"date_filter_operators",
		date_created_func:"datetime_function_filter_operators",
		date_updated:"date_filter_operators",
		date_updated_func:"datetime_function_filter_operators",
		email:"string_filter_operators",
		phone:"string_filter_operators",
		organization:"string_filter_operators",
		certificate_number:"string_filter_operators",
		verified:"boolean_filter_operators",
		_and:"verified_details_filter",
		_or:"verified_details_filter"
	}
}

export const ReturnTypes: Record<string,any> = {
	certificates:{
		id:"ID",
		user_created:"String",
		date_created:"Date",
		date_created_func:"datetime_functions",
		date_updated:"Date",
		date_updated_func:"datetime_functions",
		full_name:"String",
		ic:"String",
		phone:"String",
		cda_number:"String",
		total_days:"Int",
		test_score:"String",
		marks:"String",
		location:"String",
		course:"String",
		course_start_date:"String",
		course_end_date:"String",
		email:"String",
		certificate:"String",
		number_title:"String",
		position:"String"
	},
	certificates_aggregated:{
		group:"JSON",
		countAll:"Int",
		count:"certificates_aggregated_count",
		countDistinct:"certificates_aggregated_count",
		avg:"certificates_aggregated_fields",
		sum:"certificates_aggregated_fields",
		avgDistinct:"certificates_aggregated_fields",
		sumDistinct:"certificates_aggregated_fields",
		min:"certificates_aggregated_fields",
		max:"certificates_aggregated_fields"
	},
	certificates_aggregated_count:{
		id:"Int",
		user_created:"Int",
		date_created:"Int",
		date_updated:"Int",
		full_name:"Int",
		ic:"Int",
		phone:"Int",
		cda_number:"Int",
		total_days:"Int",
		test_score:"Int",
		marks:"Int",
		location:"Int",
		course:"Int",
		course_start_date:"Int",
		course_end_date:"Int",
		email:"Int",
		certificate:"Int",
		number_title:"Int",
		position:"Int"
	},
	certificates_aggregated_fields:{
		total_days:"Float"
	},
	Date: `scalar.Date` as const,
	datetime_functions:{
		year:"Int",
		month:"Int",
		week:"Int",
		day:"Int",
		weekday:"Int",
		hour:"Int",
		minute:"Int",
		second:"Int"
	},
	GraphQLStringOrFloat: `scalar.GraphQLStringOrFloat` as const,
	JSON: `scalar.JSON` as const,
	Mutation:{
		create_verified_details_items:"verified_details",
		create_verified_details_item:"verified_details",
		create_student_login_items:"student_login",
		create_student_login_item:"student_login",
		update_verified_details_items:"verified_details",
		update_verified_details_batch:"verified_details",
		update_verified_details_item:"verified_details",
		update_certificates_items:"certificates",
		update_certificates_batch:"certificates",
		update_certificates_item:"certificates",
		update_student_login_items:"student_login",
		update_student_login_batch:"student_login",
		update_student_login_item:"student_login"
	},
	Query:{
		verified_details:"verified_details",
		verified_details_by_id:"verified_details",
		verified_details_aggregated:"verified_details_aggregated",
		certificates:"certificates",
		certificates_by_id:"certificates",
		certificates_aggregated:"certificates_aggregated",
		student_login:"student_login",
		student_login_by_id:"student_login",
		student_login_aggregated:"student_login_aggregated"
	},
	student_login:{
		id:"ID",
		date_created:"Date",
		date_created_func:"datetime_functions",
		email:"String",
		phone:"String",
		ic:"String"
	},
	student_login_aggregated:{
		group:"JSON",
		countAll:"Int",
		count:"student_login_aggregated_count",
		countDistinct:"student_login_aggregated_count"
	},
	student_login_aggregated_count:{
		id:"Int",
		date_created:"Int",
		email:"Int",
		phone:"Int",
		ic:"Int"
	},
	verified_details:{
		id:"ID",
		user_created:"String",
		date_created:"Date",
		date_created_func:"datetime_functions",
		date_updated:"Date",
		date_updated_func:"datetime_functions",
		email:"String",
		phone:"String",
		organization:"String",
		certificate_number:"String",
		verified:"Boolean"
	},
	verified_details_aggregated:{
		group:"JSON",
		countAll:"Int",
		count:"verified_details_aggregated_count",
		countDistinct:"verified_details_aggregated_count"
	},
	verified_details_aggregated_count:{
		id:"Int",
		user_created:"Int",
		date_created:"Int",
		date_updated:"Int",
		email:"Int",
		phone:"Int",
		organization:"Int",
		certificate_number:"Int",
		verified:"Int"
	}
}

export const Ops = {
mutation: "Mutation" as const,
	query: "Query" as const
}